### PR TITLE
String format detection

### PR DESCRIPTION
**Pull request by ehooo**
- Issue #95

### CODE REVIEW

**Comment by tonybaloney** [comment]
Looks pretty good. There's a false-positive that I think is going to raise a lot of issues for users.

If you have a method on an instance called `.format()`, e.g. [pandas index format](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.format.html) it will raise the warning.

It's pretty common to have a method on a class called format, that doesn't mean its a string format. 

Is there any way you can narrow the scope?

What does the QN resolver give you?

```python
# should not
"x ".format(y, z)

z = "testing..."

# should
z.format(y, q)

# should
str(x).format(y)

# should not
f"{x}"

class Foo:
    def format(self, *args):
        pass


i = Foo()

# should not
i.format(n, o)
```

**Comment by ehooo** [comment]
I will check it.

However i don't want add introspection to resolve any expression, just exclude the "self" methods.

In case of classes you could extend from `str` so it could be affected by this vulerability, for example, [SafeString](https://github.com/django/django/blob/master/django/utils/safestring.py#L21).

By the way do you know where is the PyCharm API Doc? May be there is any way to resolve the types for some element.

Regards

**Comment by ehooo** [comment]
Hi @tonybaloney 
I just check it and now all works as expected unless the last case, because the introspection.
```python
str_cls = Foo()
# will hit, cause "str_cls" is not resolved
str_cls.format(n, o)
```
Also similar issue exists If you define the class as:
```python
class Foo(str):
    def self_format(self, *args):
        # will not hit, cause self is exclude, but with introstection must be raised
        self.format(*args)
```

I'm not sure if you want add introspection in this point or you prefere create a Helper to manage all that flow. I think that is the better option, cause resolve the variables is complicaded, and the scope of introspection must be defined. You could have dynamic loading, if, else, whiles, for, ... so resolve is `i` is or not a string class could not be easy in a big/medium code.

**Comment by tonybaloney** [comment]
I'll experiment with an introspection helper in a separate PR.

**Comment by tonybaloney** [comment]
thanks for the submission

**Pull request merged**
